"""Crawler and gate agreement against the generated demo corpus.

`~/demo-corpus` is generated by `scripts/make_demo_corpus.py` and is not part
of this repo, so every test here skips with a clear reason when it is absent.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from sidecar.domain.gate import SkipReason, is_excluded_path, screen_path
from sidecar.infrastructure.fs_crawler import FilesystemCrawler

CORPUS_ROOT = Path("~/demo-corpus").expanduser()
MANIFEST_PATH = CORPUS_ROOT / "MANIFEST.json"

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(not MANIFEST_PATH.exists(), reason=f"{CORPUS_ROOT} is absent; run `make corpus` first"),
]


def _manifest_files() -> list[dict[str, Any]]:
    return list(json.loads(MANIFEST_PATH.read_text())["files"])


def test_crawler_and_gate_agree_with_the_manifest_on_excluded_paths() -> None:
    all_paths = [entry["path"] for entry in _manifest_files()]

    # MANIFEST.json describes the corpus; it is not one of the files it describes.
    crawled = {
        str(candidate.path.relative_to(CORPUS_ROOT))
        for candidate in FilesystemCrawler().crawl(CORPUS_ROOT)
        if candidate.path.name != "MANIFEST.json"
    }

    # `is_excluded_path` is the exact rule the crawler is supposed to honor
    # when deciding what not to descend into, so it defines the truth here.
    excluded_by_directory = {path for path in all_paths if is_excluded_path(Path(path))}
    assert crawled == set(all_paths) - excluded_by_directory

    # Every path the domain rule calls directory-excluded is labeled
    # `excluded_path` in the manifest too. (The manifest also labels a few
    # bare dotfiles like `.DS_Store` this way even though they are not
    # nested under an excluded directory; a subset check tolerates that
    # without hiding a real disagreement.)
    manifest_excluded = {
        entry["path"] for entry in _manifest_files() if entry["reason"] == SkipReason.EXCLUDED_PATH.value
    }
    assert excluded_by_directory <= manifest_excluded

    # Nothing the crawler hands back is itself still excluded by path.
    for relative_path in crawled:
        decision = screen_path(CORPUS_ROOT / relative_path, size_bytes=0)
        assert decision.reason is not SkipReason.EXCLUDED_PATH
